swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "messages API"
  termsOfService: ""
  contact:
    email: "sogasusumu@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
produces:
  - "application/json"
consumes:
  - application/x-www-form-urlencoded
paths:
  /companies/{companyId}/chat_rooms:
    get:
      summary: "該当企業のチャット一覧"
      description: "指定されたcompany_idの企業"
      operationId: 'get_chatrooms_by_company_id'
      tags:
        - 'companies'
        - 'chat_rooms'
      parameters:
        - name: "companyId"
          in: "path"
          description: "chat roomsを取得したい企業のID"
          required: true
          type: "integer"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/ChatRoom'
  /companies/{companyId}/chatrooms/{chatRoomId}/messages:
    get:
      summary: "チャットのメッセージ一覧"
      description: "指定されたchatRoomIdで指定されたChatRoomのメッセージ一覧"
      operationId: 'get_chat_room_messages_by_chat_room_id'
      tags:
        - 'companies'
        - 'chatRooms'
        - 'messages'
      parameters:
        - name: "companyId"
          in: "path"
          description: "chat roomsを取得したい企業のID"
          required: true
          type: "integer"
        - name: "chatRoomId"
          in: "path"
          description: "取得したいchatRoomのID"
          required: true
          type: "integer"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Message'
definitions:
  ChatRoom:
    type: object
    properties:
      id:
        type: "integer"
        required: true
        example: 1
      companyId:
        type: "integer"
        required: true
        example: 1
      companyName:
        type: "string"
        required: true
        example: "example company"
      userId:
        type: "integer"
        required: true
        example: 1
      userName:
        type: "string"
        required: true
        example: "example user name"
      companyMessagesCounts:
        type: "integer"
        required: true
        example: 10
      userMessagesCounts:
        type: "integer"
        example: 10
      firstMessageCreatedAt:
        type: "string"
        required: true
        format: "date-time"
      lastMessageCreatedAt:
        type: "string"
        required: true
        format: "date-time"
      lastMessageSender:
        type: "string"
        required: true
    required:
      - id
      - companyId
      - companyName
      - userId
      - userName
      - companyMessagesCounts
      - userMessagesCounts
      - firstMessageCreatedAt
      - lastMessageCreatedAt
      - lastMessageSender
  Message:
    type: object
    properties:
      id:
        type: "integer"
      senderName:
        type: "string"
      body:
        type: "string"
      isSelf:
        type: "boolean"
      createdAt:
        type: "string"
        format: "date-time"
    required:
      - id
      - senderName
      - body
      - isSelf
      - createdAt
